### ISSUE TITLE
Update Dockerfile for the build ease

### ISSUE THREAD

**Issue by potetisensei** [fuzzuf/fuzzuf#108]
## Relation to existing issues

N/A

## Relation to existing roadmaps

N/A

## Motivation

As in AFL++, it is desirable that fuzzuf is built in `Dockerfile`  ( see https://github.com/AFLplusplus/AFLplusplus/blob/534b3eba143c0532e600eb6da08ac2195fa24570/Dockerfile#L81-L92 ).
Now, our `Dockerfile` just prepares the environment for build and doesn't build fuzzuf itself. 
I want to use fuzzuf only with `docker build -t fuzzuf .` under the root dir.

## Description

Just add something like `COPY . . \n cmake ...` in `Dockerfile`.
Accordingly, we need to update this one (https://github.com/fuzzuf/fuzzuf/blob/37bb92a84e4cc6c337abdfb07c96fb3dbf612702/scripts/dev_cli.sh).

This issue is good to resolve when fuzzuf-cc is ready for open and we put it into Dockerfile to combine fuzzuf and fuzzuf-cc.

## Additional context (optional)

---
> Authors of this issue must fill the checklist below when they submit it

#### Mandatory entries
- [x] The title of this issue clearly summarizes the feature request
- [x] The relations to existing issues and roadmaps are stated if they exist
- [x] Each entry above has been filled

---
> A repository maintainer will set up an asignee for each issue.
> Asignee must check this issue from the perspective of the checklist below before going through a full-fledged feature addition, and leave the initial comment.
> Copy to your comment and fill out the checklist on that occasion.

#### Optional entries
- [ ] If the feature request is going to be accepted, it has been commented
- [ ] If it is not going to be accepted and this issue is closed, it has been commented

#### Mandatory entries
- [ ] Have checked relationships to existing issues and roadmaps

---
> If an assignee is going to solve the task for this issue, consider the policy and divide the procedures into the checklist.
> Once divided, write down the checklist to the comment.
> Each step for the procedures must correspond to one single pull request. Once the PR is made, update the checklist.
> If the procedures are remained undecided, or need additional reviews, update the checklist appropriately with the discussion here.

#### Procedure checklist
- [ ] Write down the step 1
    - If you have choices rejected, add as an item here with the reasons of rejection
- [ ] Write down the step 2
    - Ditto
- [ ] ...

---
> If an assignee finishes solving the task for this issue, copy the following checklist to the comment and fill it out.

#### Optional entries
- [ ] If you have remaining tasks, relating issues have been created or updated
- [ ] If the changes against this issue affect the milestone (e.g. TODO.md), the necessity of version upgrading has already been discussed
- [ ] If new tests are required to guarantee the changes against this issue, they have been split to the checklist
- [ ] If entries in the checklist are hard to understand, that has been pointed out
- [ ] If the discussion concludes that the design concept should be documented appropriately, an assignee has checked additional documents and source codes
- [ ] If there were uncertainties during the discussion, all of them have been resolved

#### Mandatory entries
- [ ] The procedure checklist is not required to update any longer
- [ ] The PRs correspond to each entries of the checklist have adopted the best way to solve the problems as long as an assignee can come up with
- [ ] All the PRs correspond to each entries of the checklist have already been merged
- [ ] This issue can be closed

--
> If an assignee agrees to close the issue without solving the tasks relating it, describe the reasons in the comment.
> Then, copy the following checklist to the comment and fill them out.

#### Mandatory entries
- [ ] The reason to close the issue has been agreed among assignees
- [ ] This issue can be closed

**Comment by potetisensei** [comment]
Also, I found that, after building `fuzzuf` inside this Docker image, the installed `fuzzuf` does not work properly due to the fowllowing error:
```
/target_fuzzer/build/fuzzuf: error while loading shared libraries: libfuzzuf-cli-lib0.so.0: cannot open shared object file: No such file or directory
```
It look like this is because ` libfuzzuf-cli-lib0.so.0` is installed in `/usr/local/lib` but this path is not included in the library path.

**Comment by Fadis** [comment]
The library installation path is configurable in the manner of standard cmake way such as CMAKE_INSTALL_PREFIX.
So that library location is not a problem.
Just specify the path that the target system treats as library path.

I confirmed that building fuzzuf with -DCMAKE_INSTALL_PREFIX=/usr causes libraries to be placed at /usr/lib/x86_64-linux-gnu that is proper library location for Ubuntu 22.04.

**Comment by retrage** [comment]
With PR #115, fuzzuf-cc is now installed in the container image. We concluded that we can use `dev_cli.sh` as fuzzuf build with container build alternative. So I close this issue.
