### ISSUE TITLE
Build fails when using a specific architecture

### ISSUE THREAD

**Issue by key-moon** [fuzzuf/fuzzuf#21]
## Overview

The instruction for the building in [tutorial.md](https://github.com/fuzzuf/fuzzuf/blob/master/docs/tutorial.md) and [building.md](https://github.com/fuzzuf/fuzzuf/blob/master/docs/building.md) failed for my environment when executing the `cmake --build build` command with the following error:

```
error: bad value (‘tigerlake’) for ‘-march=’ switch
error: bad value (‘tigerlake’) for ‘-mtune=’ switch
```

This is due to the gcc that can be installed by apt for Ubuntu-20.04, which is gcc 9.3.0, is not supporting `tigerlake` architecture.
This issue can be resolved by specifying the binary of gcc/g++ during the configuration process, such as:

```sh
$ cmake -D CMAKE_C_COMPILER=gcc-10 -D CMAKE_CXX_COMPILER=g++-10 -B build -DCMAKE_BUILD_TYPE=Release
```

## Environment Information
```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 140
model name      : 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
stepping        : 1
microcode       : 0xffffffff
cpu MHz         : 2803.207
cache size      : 12288 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 27
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx512vbmi umip avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid movdiri movdir64b fsrm avx512_vp2intersect flush_l1d arch_capabilities
vmx flags       : vnmi invvpid ept_x_only ept_ad ept_1gb tsc_offset vtpr ept vpid unrestricted_guest ept_mode_based_exec tsc_scaling
bugs            : spectre_v1 spectre_v2 spec_store_bypass swapgs
bogomips        : 5606.41
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:
...
```

**Comment by retrage** [comment]
I tried building fuzzuf on the exactly same CPU model with containerized build. It successfully built and passed tests. I think this issue is due to the apt package rather than fuzzuf itself.

**Comment by key-moon** [comment]
It works in my environment too. But when I tried to compile a random file in the docker environment with the `-march=tigerlake` option, it failed. I think why containerized build succeeded is due to the fact that the `-march` option is only set in the release configuration, and the default configuration is set to the `build`.

https://github.com/fuzzuf/fuzzuf/blob/0412d2013f343b761edd76115670012c6e0002c0/CMakeLists.txt#L185-L188

Unsurprisingly, when I try to build with the `release` configuration like `./scripts/dev_cli.sh build --release`, the same problem happened.
