### ISSUE TITLE
fuzzing failed for the specific instrumented binary

### ISSUE THREAD

**Issue by key-moon** [fuzzuf/fuzzuf#28]
## Relation to existing issues
#9 

## Relation to existing roadmaps
N/A

## Bug explanation

If you try to fuzz a binary instrumented by `afl-clang-fast` with the `-fsanitize=address` option, it will fail with the following message if output directory already used in other fuzzing attempt.

```sh
[-]  SYSTEM ERROR : Fork server crashed

    Stop location : SetupForkServer(), /home/keymoon/ricsec/fuzzuf/executor/native_linux_executor.cpp:1055
       OS message : Success
```

If not, it will produce following message.

```sh
[-]  SYSTEM ERROR : Fork server crashed

    Stop location : SetupForkServer(), /home/keymoon/ricsec/fuzzuf/executor/native_linux_executor.cpp:1055
       OS message : No such file or directory
```

Note that fuzzing by `afl-fuzz` succeeds.

## Steps to reproduce

Execute following script
```sh
cat > main.c << EOS
#include <stdio.h>

int main(){
    char buf[8];
    scanf("%4s", buf);
    if (buf[0] == '\xde' && buf[1] == '\xad' && buf[2] == '\xbe' && buf[3] == '\xef') {
        (*(int*)(0xdeadbeef)) = 0xcafebabe;
    }
    return 0;
}
EOS

AFL_CLANG_PATH=afl-clang-fast
FUZZUF_PATH=fuzzuf
AFL_FUZZ_PATH=afl-fuzz

mkdir seeds
echo 'A' > seeds/case_0

$AFL_CLANG_PATH -fsanitize=address -o bin main.c
# fail
$FUZZUF_PATH afl --in_dir=seeds --out_dir=out-fuzzuf-$(openssl rand -hex 3) -- ./bin
# success
$AFL_FUZZ_PATH -i seeds -o out-afl-$(openssl rand -hex 3) ./bin
```

or  following steps.

```c
#include <stdio.h>

int main(){
    char buf[8];
    scanf("%4s", buf);
    if (buf[0] == '\xde' && buf[1] == '\xad' && buf[2] == '\xbe' && buf[3] == '\xef') {
        (*(int*)(0xdeadbeef)) = 0xcafebabe;
    }
    return 0;
}
```

1. Compiling the above c code by `afl-clang-fast` with `-fsanitize=address` option
3. fuzzing with `fuzzuf afl` fails
4. fuzzing with `afl-fuzz` succeeds

### Environment

- fuzzuf commit ID: 0412d2013f343b761edd76115670012c6e0002c0
- OS: Ubuntu 20.04.3 LTS on Windows 10 x86_64
- Kernel: 5.10.43.3-microsoft-standard-WSL2
- afl++ commit ID: https://github.com/AFLplusplus/AFLplusplus/commit/1d4f1e48797c064ee71441ba555b29fc3f467983

## Expected behaviors
Start fuzzing without a problem.

## Error messages, stack traces, or logs

```sh
$ cat main.c
#include <stdio.h>

int main(){
    char buf[8];
    scanf("%4s", buf);
    if (buf[0] == '\xde' && buf[1] == '\xad' && buf[2] == '\xbe' && buf[3] == '\xef') {
        (*(int*)(0xdeadbeef)) = 0xcafebabe;
    }
    return 0;
}
$ ../afl++/afl-clang-fast -fsanitize=address -o bin main.c
afl-cc++4.01a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: GCC-GCC
[!] WARNING: You are using outdated instrumentation, install LLVM and/or gcc-plugin and use afl-clang-fast/afl-clang-lto/afl-gcc-fast instead!
main.c: In function ‘main’:
main.c:5:5: warning: ignoring return value of ‘scanf’, declared with attribute warn_unused_result [-Wunused-result]
    5 |     scanf("%4s", buf);
      |     ^~~~~~~~~~~~~~~~~
afl-as++4.01a by Michal Zalewski
[+] Instrumented 35 locations (64-bit, non-hardened mode, ratio 100%).
$ ../fuzzuf/build/fuzzuf afl --in_dir=seeds -- ./bin

[-]  SYSTEM ERROR : Fork server crashed

    Stop location : SetupForkServer(), /home/keymoon/ricsec/fuzzuf/executor/native_linux_executor.cpp:1055
       OS message : Success
$ ../afl++/afl-clang-fast -fsanitize=address -o bin main.c^C
$ ../afl++/afl-fuzz -i seeds -o out -- ./bin
afl-fuzz++4.01a based on afl by Michal Zalewski and a large online community
[+] afl++ is maintained by Marc "van Hauser" Heuse, Heiko "hexcoder" Eißfeldt, Andrea Fioraldi and Dominik Maier
[+] afl++ is open source, get it at https://github.com/AFLplusplus/AFLplusplus
[+] NOTE: This is v3.x which changes defaults and behaviours - see README.md
[+] No -M/-S set, autoconfiguring for "-S default"
[*] Getting to work...
[+] Using exponential power schedule (FAST)
[+] Enabled testcache with 50 MB
[+] Generating fuzz data with a a length of min=1 max=1048576
[*] Checking core_pattern...
[!] WARNING: Could not check CPU scaling governor
[+] You have 8 CPU cores and 2 runnable tasks (utilization: 25%).
[+] Try parallel jobs - see docs/parallel_fuzzing.md.
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Checking CPU core loadout...
[+] Found a free CPU core, try binding to #0.
[*] Scanning 'seeds'...
[+] Loaded a total of 1 seeds.
[*] Creating hard links for all input files...
[*] Validating target binary...
[*] Spinning up the fork server...
[+] All right - fork server is up.
[*] No auto-generated dictionary tokens to reuse.
[*] Attempting dry run with 'id:000000,time:0,execs:0,orig:case_0'...
    len = 1, map size = 10, exec speed = 3413 us
[+] All test cases processed.
[+] Here are some useful stats:

    Test case count : 1 favored, 0 variable, 0 ignored, 1 total
       Bitmap range : 10 to 10 bits (average: 10.00 bits)
        Exec timing : 3413 to 3413 us (average: 3413 us)

[*] No -t option specified, so I'll use an exec timeout of 20 ms.
[+] All set and ready to roll!
^C

+++ Testing aborted by user +++
[+] We're done here. Have a nice day!
```

## Supplementary information (optional)

---
> Authors of this issue must fill the checklist below when they submit it

#### Mandatory entries
- [x] The title of this issue clearly summarizes the bug
- [x] The relations to existing issues and roadmaps are stated if they exist
- [x] Each entry above has been filled

---
> A repository maintainer will set up an asignee for each issue.
> Asignee must check this issue from the perspective of the checklist below before going through a full-fledged bug-fix, and leave the initial comment.
> Copy to your comment and fill out the checklist on that occasion.

#### Optional entries
- [ ] If the bug is going to be fixed, it has been commented
- [ ] If it is not going to be fixed and this issue is closed, it has been commented

#### Mandatory entries
- [ ] Have checked relationships to existing issues and roadmaps
- [ ] The minimum required information to reproduce the bug and spot the root cause is included

---
> If an assignee is going to solve the task for this issue, consider the policy and divide the procedures into the checklist.
> Once divided, write down the checklist to the comment.
> Each step for the procedures must correspond to one single pull request. Once the PR is made, update the checklist.
> If the procedures are remained undecided, or need additional reviews, update the checklist appropriately with the discussion here.

#### Procedure checklist
- [ ] Write down the step 1
    - If you have choices rejected, add as an item here with the reasons of rejection
- [ ] Write down the step 2
    - Ditto
- [ ] ...

---
> If an assignee finishes solving the task for this issue, copy the following checklist to the comment and fill it out.

#### Optional entries
- [ ] If you have remaining tasks, relating issues have been created or updated
- [ ] If the changes against this issue affect the milestone (e.g. TODO.md), the necessity of version upgrading has already been discussed
- [ ] If new tests are required to guarantee the changes against this issue, they have been split to the checklist
- [ ] If entries in the checklist are hard to understand, that has been pointed out
- [ ] If the discussion concludes that the design concept should be documented appropriately, an assignee has checked additional documents and source codes
- [ ] If there were uncertainties during the discussion, all of them have been resolved

#### Mandatory entries
- [ ] The procedure checklist is not required to update any longer
- [ ] The PRs correspond to each entries of the checklist have adopted the best way to solve the problems as long as an assignee can come up with
- [ ] All the PRs correspond to each entries of the checklist have already been merged
- [ ] This issue can be closed

--
> If an assignee agrees to close the issue without solving the tasks relating it, describe the reasons in the comment.
> Then, copy the following checklist to the comment and fill them out.

#### Mandatory entries
- [ ] The reason to close the issue has been agreed among assignees
- [ ] This issue can be closed

**Comment by key-moon** [comment]
Same issue happens when you dynamically link to `libasan.so.5`.

```sh
AFL_CLANG_PATH=../afl++/afl-clang-fast
FUZZUF_PATH=../fuzzuf/build/fuzzuf
AFL_FUZZ_PATH=../afl++/afl-fuzz

mkdir -p seeds
echo 'A' > seeds/case_0


cat > main.c << EOS
#include <stdio.h>
int main(){
    char buf[8];
    scanf("%4s", buf);
    if (buf[0] == '\xde' && buf[1] == '\xad' && buf[2] == '\xbe' && buf[3] == '\xef') {
        (*(int*)(0xdeadbeef)) = 0xcafebabe;
    }
    return 0;
}
EOS

$AFL_CLANG_PATH -o bin main.c
patchelf --add-needed libasan.so.5 bin

ldd bin

$FUZZUF_PATH afl --in_dir=seeds --out_dir=out-fuzzuf-$(openssl rand -hex 3) --  ./bin
```

There is several shared object that cause the same issue. The following is the list of so that causes the same issue in the my environment.

```
'libI810XvMC.so.1',
'libIntelXvMC.so.1',
'libLLVM-10.so.1',
'libLLVM-11.so.1',
'libLLVM-12.so.1',
'libLLVM-9.so.1',
'libasan.so.5',
'libasan.so.6',
'libboost_python38.so.1.71.0',
'libclutter-1.0.so.0',
'libevent_extra-2.1.so.7',
'libevent_openssl-2.1.so.7',
'libevent_pthreads-2.1.so.7',
'libfl.so.2',
'libfprint-2.so.2',
'libfwupd.so.2',
'libgiac.so.0',
'libgs.so.9',
'libgtk-3.so.0',
'libicudata.so',
'libicudata.so.66',
'libirs.so.1600',
'libisc.so.1601',
'liblvm2cmd.so.2.03',
'libmca_common_dstore.so.1',
'libmca_common_monitoring.so.50',
'libmca_common_ompio.so.41',
'libmca_common_sm.so.40',
'libmca_common_verbs.so.40',
'libmono-btls-shared.so',
'libmono-llvm.so.0',
'libmono-native.so.0',
'libmonosgen-2.0.so.1',
'libmpathpersist.so.0',
'libmultipath.so.0',
'libnetsnmptrapd.so.35',
'libompitrace.so.40',
'libparted-fs-resize.so.0',
'libprotobuf.so.17',
'libpypy3-c.so',
'librados.so.2',
'libratpoints-2.1.3.so',
'libsingular-gfan-4.1.1+0.6.so',
'libtheoraenc.so.1',
'libthread_db.so.1',
'libtsan.so.0',
'libunwind-coredump.so.0',
'libunwind-ptrace.so.0',
'libz3.so.4'
```


This is generated by the following script.

<details><summary>script</summary>

```py
from collections import defaultdict
import pickle
import shutil
import os
from subprocess import TimeoutExpired, check_output, run

AFL_CLANG_PATH= '../afl++/afl-clang-fast'
FUZZUF_PATH = '../fuzzuf/build/fuzzuf'
AFL_FUZZ_PATH = '../afl++/afl-fuzz'

def get_dependencies(path):
    output = check_output(f'ldd {path}', shell=True).decode()
    if "statically linked" in output: return []
    return [l.split(' => ')[0].strip() for l in output.strip().splitlines()]

CTR = 1
def uniq():
    global CTR
    CTR += 1
    return CTR

def get_patched_bin(so):
    bin_name = f'bins/bin-{uniq()}'
    shutil.copy('bin', bin_name)
    check_output(f'patchelf --add-needed {so} {bin_name}', shell=True)
    return bin_name

def check_fuzzuf(name):
    try:
        out = check_output(f'{FUZZUF_PATH} afl --in_dir=seeds --out_dir=out/fuzzuf-{uniq()} -- ./{name}; exit 0', shell=True, timeout=0.5)
    except TimeoutExpired:
        out = b''
    run('pkill fuzzuf', shell=True)
    return b'SYSTEM ERROR' not in out

os.makedirs('bins', exist_ok=True)
os.makedirs('out', exist_ok=True)
os.makedirs('seeds', exist_ok=True)
with open('seeds/case_0', 'w') as f:
    f.write('0\n')
with open('main.c', 'w') as f:
    f.write('int main(){}\n')

run(f'{AFL_CLANG_PATH} -o bin main.c', shell=True)
assert(check_fuzzuf('bin'))

bad = {}

libs = set([l.strip().split('/')[-1] for l in check_output('ldconfig -p', shell=True).decode().strip().splitlines()[1:]])
# exclude duplicate so
libs = [lib for lib in libs if all(not (l.startswith(lib) and l != lib) for l in libs)]
# exclude ld
libs = [lib for lib in libs if not lib.startswith('ld')]

# I'm too lazy to do the topological sort
for i, lib in enumerate(libs):
    print(f'[+] {i + 1} / {len(libs)}')
    patched = get_patched_bin(lib)
    deps = get_dependencies(patched)
    if set(deps) & set(bad.keys()):
        print(f'[*] bad so found in deps of {lib}')
        continue
    if check_fuzzuf(patched): continue
    print(f'[!] bad.add({lib})')
    bad[lib] = deps
    for k in list(bad.keys()):
        if k != lib and lib in bad[k]:
            print(f'[*] bad so found in deps of {k} (removed)')
            del bad[k]

print(bad)
```
</details>

**Comment by key-moon** [comment]
This can be resolved by `--exec_memlimit=0` option.

See: https://github.com/fuzzuf/fuzzuf/blob/master/docs/algorithms/afl/algorithm_en.md#how-to-use-fuzzufs-afl-cli

**Comment by potetisensei** [comment]
The ambiguous error messages of fuzzuf are simply to blame for this issue. I'm very sorry for bothering you guys.
I think there are at least two problems that can be fixed immediately. 
One is that we currently don't consider `--exec_memlimit=0` as a default option. This is due to historical reasons and probably out of date.
The other is that the message "Fork server crashed" is too coarse-grained and tells almost nothing. During the investigation of this issue, we are puzzled by seeing that message even though we just specified a wrong path of PUT that doesn't exist(!)

I think this issue should be open till we deal with these two issues (the latter can be fixed partially by just adding the "not-exist" error message and then left behind).

**Comment by retrage** [comment]
This issue is fixed by introducing `LinuxForkServerExecutor` and PR #57.
