### ISSUE TITLE
The first testcase is never used in the first cycle

### ISSUE THREAD

**Issue by ptr-yudai** [fuzzuf/fuzzuf#7]
## Relation to existing issues

N/A

## Relation to existing roadmaps

N/A

## Bug explanation

The testcase ID begins from 0 as written in PivotInputs, for example:

https://github.com/fuzzuf/fuzzuf/blob/954e5831df3c48dde9d5b596bf8032ed825a186e/include/fuzzuf/algorithms/afl/templates/afl_state.hpp#L1132

`current_entry` indicates the ID of the testcase to be used and this value is initialized to 0:

https://github.com/fuzzuf/fuzzuf/blob/954e5831df3c48dde9d5b596bf8032ed825a186e/include/fuzzuf/algorithms/afl/afl_state.hpp#L250

When selecting a seed from queue, this variable is incremented:

https://github.com/fuzzuf/fuzzuf/blob/954e5831df3c48dde9d5b596bf8032ed825a186e/include/fuzzuf/algorithms/afl/templates/afl_other_hierarflow_routines.hpp#L78

and is referenced after the increment:

https://github.com/fuzzuf/fuzzuf/blob/954e5831df3c48dde9d5b596bf8032ed825a186e/include/fuzzuf/algorithms/afl/templates/afl_other_hierarflow_routines.hpp#L114

The first testcase, `queue/id:000000,orig:XXX`, is never used in the first cycle because of this increment.

## Steps to reproduce

I wrote the following toy PUT to test the behavior.

```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char **argv) {
  unsigned char buf[0x11] = { 0 };

  if (argc < 2) return 1;

  FILE *fp = fopen(argv[1], "r");
  fread(buf, 0x10, 1, fp);
  if (buf[0] != 'd' && memcmp(&buf[1], "ead", 3) == 0) {
    buf[0x114514] = 1;
  }
  for (int j = 0; j < 0x10; j++) {
    for (int i = 0; i < buf[j]; i++) {
      buf[j+1] += i;
    }
    if (buf[j+1] == 0x10) {
      buf[j] = 0;
    }
  }
  fclose(fp);
}
```

This program crashes if the file starts with `?ead` but not `dead`. I prepared the following two seeds.
`seeds/a`:
```
deadbeefcafebabe
deadbeefcafebabe
deadbeefcafebabe
deadbeefcafebabe
deadbeefcafebabe
deadbeefcafebabe
```

`seeds/b`:
```
hogeh
ughuga
hogehog
ehughuga
hogehogehughuga
hogehogehughuga
hogehogehughuga
hogehogehughuga
```

`seeds/a` likely causes the crash but `seeds/b` will not.

When starting the fuzzing, you can confirm `PivotInputs` creates the two seeds:
`seeds/a` --> `out/queue/id:000000,orig:a`
`seeds/b` --> `out/queue/id:000001,orig:b`

You can see that only `b` is mutated during the first cycle if you check the files generated in out/queue. The crash only happens from the second cycle.

### Environment

- fuzzuf version or commit ID: 954e5831df3c48dde9d5b596bf8032ed825a186e
- OS: Ubuntu 20.04

## Expected behaviors

`current_entry` should be incremented after selecting the first testcase in the first cycle.

Suggestion for change: https://github.com/fuzzuf/fuzzuf/pull/8

## Supplementary information (optional)

---
> Authors of this issue must fill the checklist below when they submit it

#### Mandatory entries
- [x] The title of this issue clearly summarizes the bug
- [x] The relations to existing issues and roadmaps are stated if they exist
- [x] Each entry above has been filled

---
> A repository maintainer will set up an asignee for each issue.
> Asignee must check this issue from the perspective of the checklist below before going through a full-fledged bug-fix, and leave the initial comment.
> Copy to your comment and fill out the checklist on that occasion.

#### Optional entries
- [x] If the bug is going to be fixed, it has been commented
- [ ] If it is not going to be fixed and this issue is closed, it has been commented

#### Mandatory entries
- [x] Have checked relationships to existing issues and roadmaps
- [x] The minimum required information to reproduce the bug and spot the root cause is included

---
> If an assignee is going to solve the task for this issue, consider the policy and divide the procedures into the checklist.
> Once divided, write down the checklist to the comment.
> Each step for the procedures must correspond to one single pull request. Once the PR is made, update the checklist.
> If the procedures are remained undecided, or need additional reviews, update the checklist appropriately with the discussion here.

#### Procedure checklist
- [ ] Write down the step 1
    - If you have choices rejected, add as an item here with the reasons of rejection
- [ ] Write down the step 2
    - Ditto
- [ ] ...

---
> If an assignee finishes solving the task for this issue, copy the following checklist to the comment and fill it out.

#### Optional entries
- [ ] If you have remaining tasks, relating issues have been created or updated
- [ ] If the changes against this issue affect the milestone (e.g. TODO.md), the necessity of version upgrading has already been discussed
- [ ] If new tests are required to guarantee the changes against this issue, they have been split to the checklist
- [ ] If entries in the checklist are hard to understand, that has been pointed out
- [ ] If the discussion concludes that the design concept should be documented appropriately, an assignee has checked additional documents and source codes
- [ ] If there were uncertainties during the discussion, all of them have been resolved

#### Mandatory entries
- [ ] The procedure checklist is not required to update any longer
- [ ] The PRs correspond to each entries of the checklist have adopted the best way to solve the problems as long as an assignee can come up with
- [ ] All the PRs correspond to each entries of the checklist have already been merged
- [ ] This issue can be closed

--
> If an assignee agrees to close the issue without solving the tasks relating it, describe the reasons in the comment.
> Then, copy the following checklist to the comment and fill them out.

#### Mandatory entries
- [ ] The reason to close the issue has been agreed among assignees
- [ ] This issue can be closed

**Comment by RKX1209** [comment]
Thank you for reporting.
Yes. It's not correct behavior.
I've just confirmed that an original AFL increments `current_entry` [after seed selection.](https://github.com/google/AFL/blob/master/afl-fuzz.c#L8146-L8147).
