### ISSUE TITLE
Executor should show detailed error message on crash

### ISSUE THREAD

**Issue by ptr-yudai** [fuzzuf/fuzzuf#9]
## Relation to existing issues

N/A

## Relation to existing roadmaps

N/A

## Motivation

The current Native Linux Executor dies without detailed error messages when something went wrong, for example:

- PUT is not compiled by AFL
- Memory limit is not big enough to run PUT

The executor just randomly shows "Success" or "No such file or directory" as the reason of crash.
This is very confusing for the users and should be fixed.

## Description

We want to show detailed error messages at least in the 2 cases I mentioned above.
The following part of code needs revised.

https://github.com/fuzzuf/fuzzuf/blob/954e5831df3c48dde9d5b596bf8032ed825a186e/executor/native_linux_executor.cpp#L1052-L1056

## Additional context (optional)

---
> Authors of this issue must fill the checklist below when they submit it

#### Mandatory entries
- [x] The title of this issue clearly summarizes the feature request
- [x] The relations to existing issues and roadmaps are stated if they exist
- [x] Each entry above has been filled

---
> A repository maintainer will set up an asignee for each issue.
> Asignee must check this issue from the perspective of the checklist below before going through a full-fledged feature addition, and leave the initial comment.
> Copy to your comment and fill out the checklist on that occasion.

#### Optional entries
- [ ] If the feature request is going to be accepted, it has been commented
- [ ] If it is not going to be accepted and this issue is closed, it has been commented

#### Mandatory entries
- [ ] Have checked relationships to existing issues and roadmaps

---
> If an assignee is going to solve the task for this issue, consider the policy and divide the procedures into the checklist.
> Once divided, write down the checklist to the comment.
> Each step for the procedures must correspond to one single pull request. Once the PR is made, update the checklist.
> If the procedures are remained undecided, or need additional reviews, update the checklist appropriately with the discussion here.

#### Procedure checklist
- [ ] Write down the step 1
    - If you have choices rejected, add as an item here with the reasons of rejection
- [ ] Write down the step 2
    - Ditto
- [ ] ...

---
> If an assignee finishes solving the task for this issue, copy the following checklist to the comment and fill it out.

#### Optional entries
- [ ] If you have remaining tasks, relating issues have been created or updated
- [ ] If the changes against this issue affect the milestone (e.g. TODO.md), the necessity of version upgrading has already been discussed
- [ ] If new tests are required to guarantee the changes against this issue, they have been split to the checklist
- [ ] If entries in the checklist are hard to understand, that has been pointed out
- [ ] If the discussion concludes that the design concept should be documented appropriately, an assignee has checked additional documents and source codes
- [ ] If there were uncertainties during the discussion, all of them have been resolved

#### Mandatory entries
- [ ] The procedure checklist is not required to update any longer
- [ ] The PRs correspond to each entries of the checklist have adopted the best way to solve the problems as long as an assignee can come up with
- [ ] All the PRs correspond to each entries of the checklist have already been merged
- [ ] This issue can be closed

--
> If an assignee agrees to close the issue without solving the tasks relating it, describe the reasons in the comment.
> Then, copy the following checklist to the comment and fill them out.

#### Mandatory entries
- [ ] The reason to close the issue has been agreed among assignees
- [ ] This issue can be closed

**Comment by retrage** [comment]
This issue is resolved by PR #82.
